# =============================================================================
# File        : plugins.toml
# Author      : yukimemi
# Last Change : 2024/11/10 08:22:49.
# =============================================================================

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# [plugins.powerlevel10k]
# github = "romkatv/powerlevel10k"
# use = ['{{ name }}.zsh-theme']

# [plugins.spaceship]
# github = "spaceship-prompt/spaceship-prompt"

# [plugins.pure]
# github = "sindresorhus/pure"
# use = ["async.zsh", "pure.zsh"]

[plugins.zsh-show-buffer-stack]
github = "yukiycino-dotfiles/zsh-show-buffer-stack"

[plugins."zeno.zsh"]
github = "yuki-yano/zeno.zsh"
use = ['zeno.zsh']

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

# [plugins.zsh-autocomplete]
# github = "marlonrichert/zsh-autocomplete"
# apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "z-shell/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.dotfiles-sync]
local = "~/.config/zsh/sync"
use = ["*.zsh"]
apply = ["source"]

[plugins.dotfiles-defer]
local = "~/.config/zsh/defer"
use = ["*.zsh"]
apply = ["defer"]

