# vim: ft=toml ts=2 sw=2 et :

# The path of root directory to manage cloned repositories.
root = "~/src"

# Patterns to search local repositories.
includes = [
  "~/src",
  "~/.local/share/chezmoi",
  "~/.cache/nvim/dvpm",
  "~/Documents/src",
  "~/AppData/Local/nvim-data/lazy",
]

# Patterns to ignore repositories.
excludes = []
