[aliases]
l = ["log", "-r", "..", "-n", "20"]
ci = ["commit"]
lp = ["log", "-p"]
lc = ["log", "-p", "--color-words"]

[user]
name = "yukimemi"
email = "yukimemi@gmail.com"

[ui]
default-command = "log"
editor = "nvim"
