# =============================================================================
# File        : config.toml
# Author      : yukimemi
# Last Change : 2026/01/24 12:29:38
# =============================================================================

[settings]
plugin_autoupdate_last_check_duration = '1 week'
verbose = false
experimental = true

[settings.cargo]
binstall = true

[tools]
cargo-binstall = "latest"
"cargo:cargo-make" = "latest"
"cargo:bat" = "latest"
"cargo:du-dust" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:jj-cli" = "latest"
"cargo:lsd" = "latest"
"cargo:mdbook" = "latest"
"cargo:nu" = "latest"
"cargo:ripgrep" = "latest"
"cargo:ripgrep_all" = "latest"
"cargo:spyrun" = "latest"
"cargo:starship" = "latest"
"cargo:tokei" = "latest"
"cargo:zoxide" = "latest"
deno = "latest"
direnv = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
gojq = "latest"
lua-language-server = "latest"
mask = "latest"
python = "latest"
rust = "latest"
rust-analyzer = "latest"
uv = "latest"
vhs = "latest"
yt-dlp = "latest"
bun = "latest"
bottom = "latest"
starship = "latest"
zoxide = "latest"
yazi = "latest"
node = "latest"
jujutsu = "latest"
gemini-cli = "latest"
